[package]
authors = ["The Knurling-rs developers"]
categories = ["command-line-utilities", "embedded", "no-std"]
description = "Runs embedded programs just like native ones"
edition = "2018"
keywords = ["knurling", "cargo-runner"]
license = "MIT OR Apache-2.0"
name = "probe-run"
readme = "README.md"
repository = "https://github.com/knurling-rs/probe-run"
version = "0.1.3"

[dependencies]
anyhow = "1.0.32"
arrayref = "0.3.6"
colored = "2.0.0"
signal-hook = "0.1.16"
decoder = { git = "https://github.com/knurling-rs/defmt", branch = "main", optional = true }
elf2table = { git = "https://github.com/knurling-rs/defmt", branch = "main", optional = true }
env_logger = "0.7.1"
gimli = "0.22.0"
log = "0.4.11"
probe-rs = "0.9.0"
probe-rs-rtt = "0.4.0"
rustc-demangle = "0.1.16"
structopt = "0.3.15"
object = "0.21.1"

[features]
defmt = ["elf2table", "decoder"]

[workspace]
members = ["panic-probe"]
